service: serverless-appsync-bookstore
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    ${file(appsync-api.yml)}

resources:
 Resources:
   ${file(resources.yml)}
   
   